### ISSUE TITLE
Suggestion: Getting Item

### ISSUE THREAD

**Issue by emmanuelvlad** [CroaBeast/AdvancementInfo#1]
Is there a way to get the displayed item in the advancement?

**Comment by CroaBeast** [comment]
Not yet, but I can add it in the next update

**Comment by CroaBeast** [comment]
@emmanuelvlad Check the last update, now you can get the ItemStack object of the advancement item.
Tested in 1.17.1 and 1.16.5, it will help if you can test that in other versions.
