### ISSUE TITLE
Suggestion: getting more properties

### ISSUE THREAD

**Issue by emmanuelvlad** [CroaBeast/AdvancementInfo#3]
Get the `hidden` property from the advancement

**Comment by CroaBeast** [comment]
That's possible, gonna add it
Btw, do you have more options you want me to get from an advancement? I can try adding all of them

**Comment by emmanuelvlad** [comment]
Thanks a lot!

You could have:
-  `string` parent
- `boolean` show_toast
- `boolean` announce_to_chat
- `Object` rewards

**Comment by CroaBeast** [comment]
> Thanks a lot!
> 
> You could have:
> 
> * `string` parent
> * `boolean` show_toast
> * `boolean` announce_to_chat
> * `Object` rewards

I can add the first three, the last one I can add it as an object, but if you want to get all the methods from the object, you need to cast it as the NMS class AdvancementRewards, so if you want that, I can add that too

**Comment by emmanuelvlad** [comment]
Yep, perfect :ok_hand:

**Comment by CroaBeast** [comment]
> Yep, perfect 👌
> 
> Is it also possible to get the `requirements` array?

Yes, that's also possible, but the object is an `String[][]` object (a string matrix), do you want that too?

**Comment by emmanuelvlad** [comment]
Yep, it'll great to have it

**Comment by CroaBeast** [comment]
@emmanuelvlad I was searching a lot and I can get `requirements` and `criteria` as flat objects.
Because requirements is a String matrix (`String[][]`), and criteria is a Map of string and nms Criterion (`Map<String, Criterion>`), and I have no idea how I'm gonna convert that critera object to a freaking Map of an nms class (Example: `net.minecraft.server.v1_13_R2.Criterion`)
Do you want those objects to flat only objects?

**Comment by emmanuelvlad** [comment]
I think it would be better to return their type, `String[][]` for `requirements` and `Map<String, Criterion>` for `criteria`, it's great for filtering advancements such as impossible ones with `ImpossibleCriterion`

**Comment by CroaBeast** [comment]
@emmanuelvlad Like I said above, I have no idea how to convert the criteria object into a Map (and I think is not that simple to just cast it using `Map<String, Criterion>`), also I need to get the criterion class depending on the version and use it in the map.

I already get the String matrix for the requirements, but I can not get th map object as a map, sorry

**Comment by emmanuelvlad** [comment]
No probs, thank you!

**Comment by CroaBeast** [comment]
All the objects getter are done, I was reworking the proyect a bit to do it more legible. 
Also, you can add it into your project using maven or gradle! If you want to still copy paste the classes, you can still do that

**Comment by CroaBeast** [comment]
@emmanuelvlad check the new update! if you are using maven or gradle, you can use the RELEASE_TAG `254f817f51` because JitPack doesn't work properly :D

**Comment by CroaBeast** [comment]
Gonna close this ticket, have a great day!

**Comment by emmanuelvlad** [comment]
Awesome, it works great!

Thanks for your work dude!
