### ISSUE TITLE
Support 1.20.3+

### ISSUE THREAD

**Issue by TheFaser** [CroaBeast/AdvancementInfo#7]
In version 1.20.3 they changed the achievements again and now to get display you need to access "c" again

```java
Object display = NMSUtil.getObject(nmsAdv, IS_19_4 && !IS_20_3 ? "d" : "c");
```

**Comment by CroaBeast** [comment]
Sorry for the late response, having personal issues. I'll update it this month. Thanks for reporting

**Comment by CroaBeast** [comment]
Please update to 3.0
